# This is a GitHub App Manifest. These settings will be used by default when
# initially configuring your GitHub App.
#
# NOTE: changing this file will not update your GitHub App settings.
# You must visit github.com/settings/apps/your-app-name to edit them.
#
# Read more about configuring your GitHub App:
# https://probot.github.io/docs/development/#configuring-a-github-app
#
# Read more about GitHub App Manifests:
# https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/

# The list of events the GitHub App subscribes to.
# Uncomment the event names below to enable them.
default_events:
  - installation_target
  - meta
  - branch_protection_rule
  - fork
  - public
  - push
  - repository
  - repository_dispatch
  - workflow_dispatch
  - workflow_job
  - workflow_run

# The set of permissions needed by the GitHub App. The format of the object uses
# the permission name for the key (for example, issues) and the access type for
# the value (for example, write).
# Valid values are `read`, `write`, and `none`
default_permissions:
  # Repository actions
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-actions
  actions: write

  # Repository creation, deletion, settings, teams, and collaborators.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-administration
  administration: write

  # Repository contents, commits, branches, downloads, releases, and merges.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents
  contents: write

  # Search repositories, list collaborators, and access repository metadata.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-metadata
  metadata: read

  # Manage access to an organization.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#organization-permissions-for-administration
  organization_administration: read

  # Organization members and teams.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#organization-permissions-for-members
  members: read

  # Manage a user's email addresses.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#user-permissions-for-email-addresses
  email_addresses: read

  # Copy workflow files to the repository.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-workflows
  workflows: write

  # Set custom properties for the repository.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-custom-properties
  custom_properties: write

  # Set custom properties for the organization.
  # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#organization-permissions-for-custom-properties
  organization_custom_properties: admin

# The name of the GitHub App. Defaults to the name specified in package.json
name: private-mirrors

# The homepage of your GitHub App.
url: https://github.com/github-community-projects/private-mirrors

# A description of the GitHub App.
description: A GitHub App that allows you to contribute upstream using private mirrors of public repos.

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app. Default: true
public: true
