name: Run Build

on:
  - push
  - workflow_dispatch
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: NEXT_TELEMETRY_DISABLED=1 npm run build
