name: Build Docker Image

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CI Environment
        run: mv .env.example .env

      - name: Build Docker image
        run: docker build -t internal-contribution-forks .
