name: Build Docker Image

on:
  - push
  - workflow_dispatch
  - pull_request

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4

      - name: Build Docker image
        run: docker build -t internal-contribution-forks .
