name: Run Lint

on:
  - push
  - workflow_dispatch
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
