name: Run Jest Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Setup CI Environment
        run: mv .env.example .env

      - name: Run Jest Tests
        run: npm test
